version: '3'
services:
  weatleyapi:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - 'prisma'
    volumes:
      - .:/app
    command: ["./wait-for-it.sh", "prisma:4466", "--", "./bootstrap.sh"]
  prisma:
    image: prismagraphql/prisma:1.30.1
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mongo
            uri: 'mongodb://prisma:prisma@mongo'
  mongo:
    image: mongo:4.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
